### ISSUE TITLE
docker status, not a valid command

### ISSUE THREAD

**Issue by arosales** [juju-solutions/layer-swarm#10]
The readmen indicates to run 
`docker status`

However that is not a valid Docker command. To get status I suggest:
`docker stats`
or 
`docker ps -a`

**Comment by lazypower** [comment]
I'm confused on where you found `docker status` in the readme. I'm not able to locate that at all.

here's output from a grep -ri 'docker status' in the charm dir:

```
/README.md:coordination from the swarm leader. (This is visible in `juju status` output)
./README.md:The final line of the usage commands will display information about the status
```

I see juju status which is correct. the other command references `docker info` which is used to spit out information about the running engine or cluster, respectively how you have your client context set.

**Comment by arosales** [comment]
Sorry this was supposed to be against the bundle.
